---

- name: Ensure directory exists for MySQL docker-compose
  file:
    path: /mysql/
    state: directory
    mode: '0755'

- name: Upload docker-compose file
  copy:
    src: docker-compose.yml
    dest: /mysql/docker-compose.yml

- name: Deploy MySQL using docker-compose
  command:
    cmd: docker-compose up -d
    chdir: /mysql/  # 这里指定docker-compose.yml所在的目录

