Vagrant.configure("2") do |config|

    # main & default: normal OS series...
    config.vm.define "main", primary: true do |node|
        # node.vm.box = "ubuntu/trusty64"
        # node.vm.box = "ubuntu/xenial64"
        node.vm.box = "ubuntu/focal64"
        # node.vm.network "private_network", ip: "192.168.56.10"

        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "setup.yml"
            ansible.extra_vars = {
              ansible_python_interpreter: "/usr/bin/python3",
              ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
            }
            # ansible.sudo = true
        end
    end
end
