   
- hosts: 127.0.0.1
  connection: local
  roles:
    - set-time
    - set-hostname
  handlers:
    - include: 'handlers/main.yml'
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
  tasks:
    - include: 'tasks/main.yml'
